apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload-name
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: workload-name
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sample-accelerators/workload-name
      ref:
        branch: main
